name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt 
      - name: Analyse the ChessBot Project
        working-directory: ./chessbot
        run: |
          pylint --rcfile="../.pylintrc" `ls -R|grep .py$|xargs`
